name: Playwright CI on macOS

# Trigger the workflow on push and pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      grep:
        description: 'tests to grep '
        required: false
        default: ''
      run:
        required: false
      testomatio:
        required: false

# Define the job for running Playwright tests on macOS
jobs:
  test:
    runs-on: macos-latest

    # Define the steps to set up and run the tests
    steps:
      # Check out the repository
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Gen BDD steps
      - name: npx bddgen
        run: npx bddgen
        
      # Run Playwright tests
      - name: Run Playwright tests
        run: TESTOMATIO=tstmt_xIsv5lZjVgOY8F-6SNu5CWr-csFz6J1Oxw1732210878 npx playwright test
